//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GurmeetDhaliwal_PreSCreening
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAr
    {
        public int ID { get; set; }
        public string Manufacture { get; set; }
        public string Make { get; set; }
        public System.DateTime Release_Year { get; set; }
        public string Color { get; set; }
        public int Seating { get; set; }
    }
}
